<a href="https://colab.research.google.com/github/dscamacho333/Data_Science_Course/blob/main/Pandas_Inmuebles_CDMX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas es una biblioteca de código abierto en Python utilizada para el análisis de datos. Proporciona herramientas poderosas y fáciles de usar para la manipulación y análisis de datos en formatos de tablas, como CSV, Excel, SQL y muchos otros.

Con Pandas, podemos cargar datos desde diversas fuentes en un objeto llamado DataFrame, que es una tabla de datos similar a una hoja de cálculo de Excel. Luego, podemos trabajar con estos datos realizando operaciones como filtrar, ordenar, agregar y transformar.

La biblioteca Pandas es ampliamente utilizada en aplicaciones de ciencia de datos, aprendizaje automático, finanzas y análisis empresarial. Es una herramienta esencial para profesionales que trabajan con datos, como analistas de datos, científicos de datos e ingenieros de datos.

En resumen, la biblioteca Pandas es una herramienta de alto rendimiento para el análisis de datos en Python, que permite trabajar con datos en diferentes formatos y realizar diversas operaciones para manipular, analizar y visualizar los datos de manera eficiente y productiva.

Documentation: https://pandas.pydata.org/

# **Pandas**

## **Importing database**

In [ ]:
# Import pandas
import pandas as pd

# Define dataset url
url : str = 'https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv'

      Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0          Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                       Casa;Polanco;2;0;1;100;24500.0;;
2      Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3      Departamento;Centro Histórico;1;0;0;15;2800.0;...
4          Departamento;Del Valle;1;0;0;48;2800.0;805.0;
...                                                  ...
25116  Cochera/Estacionamiento;Centro Histórico;0;0;0...
25117  Cocineta;Centro Histórico;0;0;0;27;2800.0;1225...
25118  Departamento;Mixcoac;2;1;0;48;4900.0;1781.5;129.5
25119  Departamento;Lomas de Chapultepec;2;0;0;70;105...
25120  Conjunto Comercial/Sala;Centro Histórico;0;0;0...

[25121 rows x 1 columns]

In [ ]:
# Read csv without separation
pd.read_csv(
    url
)

      Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0          Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                       Casa;Polanco;2;0;1;100;24500.0;;
2      Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3      Departamento;Centro Histórico;1;0;0;15;2800.0;...
4          Departamento;Del Valle;1;0;0;48;2800.0;805.0;
...                                                  ...
25116  Cochera/Estacionamiento;Centro Histórico;0;0;0...
25117  Cocineta;Centro Histórico;0;0;0;27;2800.0;1225...
25118  Departamento;Mixcoac;2;1;0;48;4900.0;1781.5;129.5
25119  Departamento;Lomas de Chapultepec;2;0;0;70;105...
25120  Conjunto Comercial/Sala;Centro Histórico;0;0;0...

[25121 rows x 1 columns]

In [ ]:
# Read separated csv and assigning the result into data var
data : pd.DataFrame = pd.read_csv(
    url,
    sep=';'
)

# Show data
data

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [ ]:
# Method to show first five rows of data
data.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN

In [ ]:
# Method to show last five rows of data
data.tail()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [ ]:
# Show first 10 records (n = number of records you wanna show)

data.head(
    n=10
)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
5,Casa de Condominio,Santa Fe,5,4,5,750,77000.0,NaN,NaN
6,Conjunto Comercial/Sala,Centro Histórico,0,3,0,695,122500.0,67175.5,10605.0
7,Departamento,Centro Histórico,1,0,0,36,4200.0,NaN,NaN
8,Departamento,Condesa,1,0,1,40,7000.0,1963.5,175.0
9,Cocineta,Condesa,1,0,0,27,6300.0,1753.5,NaN

In [ ]:
# Method to get a random sample from dataset

data.sample(
    n=10
)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
10878,Conjunto Comercial/Sala,Santa Fe,0,1,1,50,8750.0,4977.0,700.0
23496,Departamento,Santa Fe,4,3,4,230,56000.0,NaN,NaN
116,Departamento,El Rosedal,2,1,0,50,3850.0,NaN,NaN
8906,Departamento,Narvarte,3,1,0,102,5950.0,2191.0,NaN
1897,Departamento,Roma,2,1,1,84,17500.0,3874.5,735.0
12587,Edificio Completo,Juárez,0,10,0,1320,297500.0,92400.0,NaN
8393,Departamento,Ciudad de los Deportes,2,1,1,79,5250.0,2030.0,273.0
2593,Galpón/Depósito/Almacén,Santa María Aztahuacán,0,15,0,1640,87500.0,3.5,NaN
2585,Departamento,Condesa,3,1,0,140,12950.0,4984.0,1151.5
5517,Departamento,Narvarte,2,0,0,68,6300.0,1400.0,84.0

Pandas ofrece diversas funciones para importar y exportar datos en diferentes formatos. Las principales funciones de Pandas para importar datos son las siguientes:

read_csv(): Esta función se utiliza para leer archivos CSV (Comma Separated Values), que son archivos de texto que contienen datos separados por comas. Es posible proporcionar varios parámetros para personalizar la lectura del CSV, como el delimitador, el encabezado, el tipo de codificación, entre otros.

read_excel(): Esta función se utiliza para leer archivos de Excel (.xls o .xlsx) y crear un DataFrame a partir de los datos.

read_json(): Esta función se utiliza para leer archivos JSON (JavaScript Object Notation), que son archivos de texto que contienen datos en formato de objeto JavaScript.

read_html(): Esta función se utiliza para leer tablas HTML, que son estructuras de datos organizadas en formato de tabla en una página web.

read_sql(): Esta función se utiliza para leer datos de una base de datos relacional, como MySQL, PostgreSQL y SQL Server. Pandas es capaz de importar datos de diferentes maneras, lo que permite ajustar parámetros como la consulta, el nombre de la tabla y el tipo de datos de las columnas.

## **Initial Data Exploration**

In [ ]:
data.sample(
    n=5
)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
3754,Departamento,Coyoacán,3,1,2,242,34996.5,NaN,34737.5
11801,Departamento,Juárez,2,1,0,71,7700.0,2537.5,381.5
753,Tienda/Salón,Santa Fe,0,10,0,440,70000.0,52500.0,NaN
20898,Departamento,Roma,1,0,0,40,2450.0,525.0,NaN
6672,Conjunto Comercial/Sala,Centro Histórico,0,0,0,219,21000.0,11644.5,3668.0

In [ ]:
# Attribute that contains how many row & columns there are Tuple(number_rows, number_columns)

data.shape

(25121, 9)

In [ ]:
# Attribute that contains what columns out dabase has

data.columns

Index(['Tipo', 'Colonia', 'Habitaciones', 'Garages', 'Suites', 'Area', 'Valor',
       'Condominio', 'Impuesto'],
      dtype='object')

In [ ]:
# Method to show a brief description of the data.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25121 entries, 0 to 25120
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tipo          25121 non-null  object
 1   Colonia       25121 non-null  object
 2   Habitaciones  25121 non-null  int64
 3   Garages       25121 non-null  int64
 4   Suites        25121 non-null  int64
 5   Area          25121 non-null  int64
 6   Valor         25107 non-null  float64
 7   Condominio    22495 non-null  float64
 8   Impuesto      18037 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [ ]:
# This is the way to access to an specific column info within the database
data['Tipo']

0                       Cocineta
1                           Casa
2        Conjunto Comercial/Sala
3                   Departamento
4                   Departamento
                  ...
25116    Cochera/Estacionamiento
25117                   Cocineta
25118               Departamento
25119               Departamento
25120    Conjunto Comercial/Sala
Name: Tipo, Length: 25121, dtype: object

In [ ]:
# This is the way to access to many specific columns info within the database
data[['Habitaciones', 'Valor']]

       Habitaciones    Valor
0                 1   5950.0
1                 2  24500.0
2                 0  18200.0
3                 1   2800.0
4                 1   2800.0
...             ...      ...
25116             0  49000.0
25117             0   2800.0
25118             2   4900.0
25119             2  10500.0
25120             0  22750.0

[25121 rows x 2 columns]

Para practicar los métodos aprendidos a lo largo de esta lección y aprender nuevos, realizaremos algunos análisis utilizando un archivo CSV diferente: alumnos.csv.

Importa el archivo alumnos.csv y almacena su contenido en un DataFrame de Pandas.

Visualiza las primeras 7 filas del DataFrame y las últimas 5.

Verifica la cantidad de filas y columnas en este DataFrame.

Explora las columnas del DataFrame y analiza los tipos de datos presentes en cada columna.

Extra: Calcula algunas estadísticas descriptivas básicas de los datos en el DataFrame (media, desviación estándar, etc.). Pista: busca el método "describe".

Si necesitas ayuda, en la sección "Opinión del Instructor" puedes encontrar algunas formas de resolver los desafíos propuestos anteriormente.

In [ ]:
alumni_url : str = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'

In [ ]:
alumni_dataframe : pd.DataFrame = pd.read_csv(
    alumni_url,
    sep=','
)

alumni_dataframe

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [ ]:
alumni_dataframe.head(
    n=7
)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True

In [ ]:
alumni_dataframe.tail(
    n=5
)

    Nombre  Edad  Nota   Aprobado
13  Miriam    25   9.0       True
14   Pablo    37   NaN      False
15  Milena    29   7.0       True
16   Lucas    33   NaN      False
17   Nadia    34   8.0  Verdadero

In [ ]:
alumni_dataframe.shape

(18, 4)

In [ ]:
alumni_dataframe['Nombre']

0      Alberto
1          Ana
2       Camila
3        David
4        Brian
5        Bruna
6      Daniela
7       Carlos
8       Alicia
9       Victor
10      Danilo
11     Ignacio
12    Stephany
13      Miriam
14       Pablo
15      Milena
16       Lucas
17       Nadia
Name: Nombre, dtype: object

In [ ]:
alumni_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 708.0+ bytes

In [ ]:
alumni_dataframe.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000